### PR TITLE
Throw CompositeTaskFailedException for context.allOf

### LINKED ISSUE #54: TaskOrchestrationContext.allOf should throw TaskFailureException instead of RuntimeException
The implementation of this method in TaskOrchestrationExecutor.java currently throws a `RuntimeException` if any of the inner tasks fails. This seems wrong because tasks are only supposed to fail with `TaskFailedException`.

One challenge is that `TaskFailedException` is designed to represent a single named task. We may need to create a new exception type for composite exceptions. Alternatively, we could surface the details of the first exception. It may be useful to use the current .NET implementation design as a reference for this design.

As part of this work item, we should also do the following:
- [ ] Update the API documentation for `TaskOrchestrationContext.allOf` to accurately reflect the expected exception behavior
- [ ] Write a unit or integration test that ensures the correct behavior

### PR DESCRIPTION
**Pull request by shreyas-gopalakrishna**
TaskOrchestrationContext.allOf should throw TaskFailureException instead of RuntimeException
- code changes 
- unit tests 
- documentation changes

resolves #54 

### Pull request checklist

* [ ] My changes **do not** require documentation changes
    * [x] Otherwise: Documentation issue linked to PR
* [ ] My changes are added to the `CHANGELOG.md`
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

File: client/src/main/java/com/microsoft/durabletask/TaskOrchestrationExecutor.java [hunk 1]
```diff
@@ -166,30 +164,39 @@ public <V> Task<V> completedTask(V value) {
...
                     } catch (Exception ex) {
-                        // TODO: Better exception message than this
-                        // TODO: This needs to be a TaskFailedException or some other documented exception type.
-                        //       https://github.com/microsoft/durabletask-java/issues/54
-                        throw new RuntimeException("One or more tasks failed.", ex);
+                        exceptions.add(ex);
                     }
                 }
 
+                if(exceptions.size() > 0){
```
Comment (shreyas-gopalakrishna) [inline client/src/main/java/com/microsoft/durabletask/TaskOrchestrationExecutor.java:189]: @cgillum @kaibocai the thought was to catch exceptions into a list and use that to throw a CompositeTaskFailedException but we cannot throw it from here. Any ideas how we could handle this?

File: client/src/main/java/com/microsoft/durabletask/TaskOrchestrationExecutor.java [hunk 2]
```diff
@@ -166,30 +164,39 @@ public <V> Task<V> completedTask(V value) {
...
-        public <V> Task<List<V>> allOf(List<Task<V>> tasks) {
+        public <V> Task<List<V>> allOf(List<Task<V>> tasks) throws CompositeTaskFailedException{
             Helpers.throwIfArgumentNull(tasks, "tasks");
 
             CompletableFuture<V>[] futures = tasks.stream()
                     .map(t -> t.future)
                     .toArray((IntFunction<CompletableFuture<V>[]>) CompletableFuture[]::new);
 
-            return new CompletableTask<>(CompletableFuture.allOf(futures).thenApply(x -> {
+//            List<Exception> exceptions = new ArrayList<>(futures.length);
```
Comment (shreyas-gopalakrishna) [inline client/src/main/java/com/microsoft/durabletask/TaskOrchestrationExecutor.java:174]: exceptions cannot be collected here as I think all futures wouldn't be completed here yet.

Comment (kaibocai) [reply client/src/main/java/com/microsoft/durabletask/TaskOrchestrationExecutor.java:174]: Sorry I don't get it, why can't we move the `exceptions` list out at this place? It doesn't matter if the futures completed or not when we initialize the exceptions list right.

File: client/src/test/java/com/microsoft/durabletask/IntegrationTests.java [hunk 3]
```diff
@@ -778,4 +783,41 @@ void purgeInstanceFilter() {
...
+                            .mapToObj(i -> ctx.callActivity(activityName, i, Integer.class))
+                            .collect(Collectors.toList());
+
+                    // Wait for all tasks to complete
+                    List<Integer> results;
+                    try {
+                        results = ctx.allOf(parallelTasks).await();
+                        ctx.complete(results);
+                    } catch (CompositeTaskFailedException e) {
+                        e.printStackTrace();
```
Comment (cgillum) [inline client/src/test/java/com/microsoft/durabletask/IntegrationTests.java:807]: This test verifies that the correct exception type was thrown but doesn't verify that it's actually a composite containing details about each of the individual failures. We should make this test more comprehensive and actually inspect the contents of the exception.

Comment (shreyas-gopalakrishna) [reply client/src/test/java/com/microsoft/durabletask/IntegrationTests.java:807]: Yes, I am yet to add that since CompositeTaskFailedException is current not being raised here and second catch block catches the Exception. 

image

File: client/src/main/java/com/microsoft/durabletask/CompositeTaskFailedException.java [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+import java.util.List;
+
+public class CompositeTaskFailedException extends Exception{
+    private final List<Exception> exceptions;
+
+    public CompositeTaskFailedException() {
+        this.exceptions = new ArrayList<>();
+    }
+
+    public CompositeTaskFailedException(List<Exception> exceptions) {
```
Comment (cgillum) [inline client/src/main/java/com/microsoft/durabletask/CompositeTaskFailedException.java:13]: Let's make all these constructors package-internal (remove `public`). We don't want to add more to the public API surface area than absolutely necessary.

File: client/src/main/java/com/microsoft/durabletask/CompositeTaskFailedException.java [hunk 5]
```diff
@@ -0,0 +1,41 @@
+package com.microsoft.durabletask;
+
+import java.util.ArrayList;
+import java.util.List;
+
+public class CompositeTaskFailedException extends Exception{
```
Comment (cgillum) [inline client/src/main/java/com/microsoft/durabletask/CompositeTaskFailedException.java:6]: Let's add JavaDoc comments to all the public APIs. Please refer to the existing JavaDocs in this code as examples for style guidelines.

File: client/src/main/java/com/microsoft/durabletask/CompositeTaskFailedException.java [hunk 6]
```diff
@@ -0,0 +1,41 @@
+package com.microsoft.durabletask;
```
Comment (cgillum) [inline client/src/main/java/com/microsoft/durabletask/CompositeTaskFailedException.java:1]: Please add the license header for new files.

File: client/src/main/java/com/microsoft/durabletask/TaskOrchestrationExecutor.java (hunk 1 above)
Comment (cgillum) [reply client/src/main/java/com/microsoft/durabletask/TaskOrchestrationExecutor.java:189]: Correct. You can't throw it from here. It has to be thrown from the `.await()` call of the `Task<List<V>>` object that we return from this method - i.e. `completableTask`.  You may need to set some state in this object somehow so that we know what to throw.

File: client/src/test/java/com/microsoft/durabletask/IntegrationTests.java [hunk 7]
```diff
@@ -317,7 +317,7 @@ void termination() {
     }
 
     @Test
-    void activityFanOut() throws IOException {
+    void activityFanOut() throws TaskFailedException {
```
Comment (cgillum) [inline client/src/test/java/com/microsoft/durabletask/IntegrationTests.java:320]: Why do we need this change?

File: samples/src/main/java/io/durabletask/samples/FanOutFanInPattern.java [hunk 8]
```diff
@@ -70,7 +70,12 @@ public TaskOrchestration create() {
                             .collect(Collectors.toList());
 
                     // Fan-in to get the total word count from all the individual activity results.
-                    List<Integer> allWordCountResults = ctx.allOf(tasks).await();
+                    List<Integer> allWordCountResults;
+                    try {
+                        allWordCountResults = ctx.allOf(tasks).await();
+                    } catch (CompositeTaskFailedException e) {
```
Comment (cgillum) [inline samples/src/main/java/io/durabletask/samples/FanOutFanInPattern.java:76]: Since you had to change this sample, it means we're making a breaking change. I wonder if we should instead make `CompositeTaskFailedException` a runtime exception to avoid the breaking change. Alternatively, we should consider updating `TaskOrchestration.run` to catch this exception so that developers don't have to.

**Review by cgillum — COMMENTED** [review]
Some thoughts

File: client/src/test/java/com/microsoft/durabletask/IntegrationTests.java (hunk 3 above)
Comment (cgillum) [reply client/src/test/java/com/microsoft/durabletask/IntegrationTests.java:807]: Something to consider: when designing and implementing new APIs, it’s a best practice to write the test first before completing the implementation. In this way, you’re designing for the customer ideal experience since the test represents the customer experience. This is the spirit behind the TDD movement. I recommend looking into this practice moving forward.

File: client/src/main/java/com/microsoft/durabletask/CompositeTaskFailedException.java [hunk 9]
```diff
@@ -0,0 +1,56 @@
...
+import java.util.List;
+
+/**
+ * Exception that gets thrown when multiple {@link Task}s for an activity or sub-orchestration fails with an
+ * unhandled exception.
+ * <p>
+ * Detailed information associated with each task failure can be retrieved using the {@link #getExceptions()}
+ * method.
+ */
+public class CompositeTaskFailedException extends RuntimeException {
```
Comment (kaibocai) [inline client/src/main/java/com/microsoft/durabletask/CompositeTaskFailedException.java:15]: Just to check if here is uncheck exception then when cx using `allOf` method they won't know to catch the specific CompositeTaskFailedException right. I believe we will document this for `allOf` method somewhere. 
Also should we update the API javadoc for `allOf` mehtod.

File: client/src/test/java/com/microsoft/durabletask/IntegrationTests.java [hunk 10]
```diff
@@ -778,4 +779,54 @@ void purgeInstanceFilter() {
...
+            assertEquals(OrchestrationRuntimeStatus.FAILED, instance.getRuntimeStatus());
+
+            List<?> output = instance.readOutputAs(List.class);
+            assertNull(output);
+
+            FailureDetails details = instance.getFailureDetails();
+            assertNotNull(details);
+            assertEquals("One or more tasks failed.", details.getErrorMessage());
+            assertEquals("com.microsoft.durabletask.CompositeTaskFailedException", details.getErrorType());
+            assertNotNull(details.getStackTrace());
```
Comment (kaibocai) [inline client/src/test/java/com/microsoft/durabletask/IntegrationTests.java:829]: We can also add a exception size assert to double check here. Just to double check :)

Comment (shreyas-gopalakrishna) [reply client/src/test/java/com/microsoft/durabletask/IntegrationTests.java:829]: Yes, this is done in line 802

File: client/src/main/java/com/microsoft/durabletask/CompositeTaskFailedException.java (hunk 9 above)
Comment (shreyas-gopalakrishna) [reply client/src/main/java/com/microsoft/durabletask/CompositeTaskFailedException.java:15]: I can document it as part of the Javadoc.

**Review by kaibocai — APPROVED** [review]

File: client/src/main/java/com/microsoft/durabletask/CompositeTaskFailedException.java [hunk 11]
```diff
@@ -0,0 +1,56 @@
...
+        this.exceptions = exceptions;
+    }
+
+    /**
+     * Gets a list of exceptions that occurred during execution of a group of {@link Task}
+     * These exceptions include details of the task failure and exception information
+     *
+     * @return a list of exceptions
+     */
+    List<Exception> getExceptions() {
```
Comment (cgillum) [inline client/src/main/java/com/microsoft/durabletask/CompositeTaskFailedException.java:52]: This needs to be public.

File: client/src/test/java/com/microsoft/durabletask/IntegrationTests.java [hunk 12]
```diff
@@ -778,4 +779,54 @@ void purgeInstanceFilter() {
...
+                        ctx.complete(results);
+                    }catch (CompositeTaskFailedException e){
+                        assertNotNull(e);
+                        assertEquals(2, e.getExceptions().size());
+                        assertEquals(ExecutionException.class, e.getExceptions().get(0).getClass());
+                        assertEquals(ExecutionException.class, e.getExceptions().get(1).getClass());
+                        assertEquals(TaskFailedException.class, e.getExceptions().get(0).getCause().getClass());
+                        assertEquals(TaskFailedException.class, e.getExceptions().get(1).getCause().getClass());
+                        assertTrue(e.getExceptions().get(0).getCause().getMessage().contains("unhandled exception: / by zero"));
+                        assertTrue(e.getExceptions().get(1).getCause().getMessage().contains("unhandled exception: / by zero"));
```
Comment (cgillum) [inline client/src/test/java/com/microsoft/durabletask/IntegrationTests.java:808]: I have concerns about what the full error message will look like. Can we update the test to do an `.equals` check instead of `.contains`?

File: client/src/test/java/com/microsoft/durabletask/IntegrationTests.java [hunk 13]
```diff
@@ -778,4 +779,54 @@ void purgeInstanceFilter() {
...
+            OrchestrationMetadata instance = client.waitForInstanceCompletion(instanceId, defaultTimeout, true);
+            assertNotNull(instance);
+            assertEquals(OrchestrationRuntimeStatus.FAILED, instance.getRuntimeStatus());
+
+            List<?> output = instance.readOutputAs(List.class);
+            assertNull(output);
+
+            FailureDetails details = instance.getFailureDetails();
+            assertNotNull(details);
+            assertEquals("One or more tasks failed.", details.getErrorMessage());
```
Comment (cgillum) [inline client/src/test/java/com/microsoft/durabletask/IntegrationTests.java:827]: This doesn't seem very helpful. Can we include more information, like which task failed (using the task name and/or ID if available)?

File: client/src/main/java/com/microsoft/durabletask/TaskOrchestrationExecutor.java [hunk 14]
```diff
@@ -173,23 +171,32 @@ public <V> Task<List<V>> allOf(List<Task<V>> tasks) {
...
+            return new CompletableTask<>(CompletableFuture.allOf(futures)
+                    .thenApply(x -> {
+                        List<V> results = new ArrayList<>(futures.length);
+
+                        // All futures are expected to be completed at this point
+                        for (CompletableFuture<V> cf : futures) {
+                            try {
+                                results.add(cf.get());
+                            } catch (Exception ex) {
+                                throw new RuntimeException("One or more tasks failed.", ex);
```
Comment (cgillum) [inline client/src/main/java/com/microsoft/durabletask/TaskOrchestrationExecutor.java:183]: Do we still need this catch/rethrow here if we have the `exceptionally` handler? I don't understand why we would throw this exception here with the exact same text as the `CompositeTaskFailedException` on line 197.

Comment (shreyas-gopalakrishna) [reply client/src/main/java/com/microsoft/durabletask/TaskOrchestrationExecutor.java:183]: `cf.get()` throws checked exceptions, we will have to catch that. We do not need the rethrow as exceptions will be handled by `exceptionally`. I'm thinking we just log exception details in the catch block, is that good?

Comment (cgillum) [reply client/src/main/java/com/microsoft/durabletask/TaskOrchestrationExecutor.java:183]: No, I don't think we should log individual task failures inside this method. Those exceptions should be getting logged elsewhere already. Instead, I think we need to call `results.add(...)` with a default/null value.

File: client/src/main/java/com/microsoft/durabletask/TaskOrchestrationContext.java [hunk 15]
```diff
@@ -76,6 +76,16 @@ public interface TaskOrchestrationContext {
      * List<String> orderedResults = ctx.allOf(List.of(t1, t2, t3)).await();
      * }</pre>
      *
+     * Exceptions in any of the given tasks results in an unchecked {@link CompositeTaskFailedException}.
+     * This exception can be inspected to obtain failure details of individual {@link Task}s.
+     * <pre>{@code
+     * try {
+     *     List<String> orderedResults = ctx.allOf(List.of(t1, t2, t3)).await();
+     * } catch{
+     *     e.getExceptions()
```
Comment (cgillum) [inline client/src/main/java/com/microsoft/durabletask/TaskOrchestrationContext.java:85]:
```suggestion
     *     List<Exception> exceptions = e.getExceptions()
```

File: client/src/main/java/com/microsoft/durabletask/TaskOrchestrationContext.java [hunk 16]
```diff
@@ -76,6 +76,16 @@ public interface TaskOrchestrationContext {
      * List<String> orderedResults = ctx.allOf(List.of(t1, t2, t3)).await();
      * }</pre>
      *
+     * Exceptions in any of the given tasks results in an unchecked {@link CompositeTaskFailedException}.
+     * This exception can be inspected to obtain failure details of individual {@link Task}s.
+     * <pre>{@code
+     * try {
+     *     List<String> orderedResults = ctx.allOf(List.of(t1, t2, t3)).await();
+     * } catch{
```
Comment (cgillum) [inline client/src/main/java/com/microsoft/durabletask/TaskOrchestrationContext.java:84]:
```suggestion
     * } catch (CompositeTaskFailedException e) {
```

File: client/src/test/java/com/microsoft/durabletask/IntegrationTests.java [hunk 17]
```diff
@@ -778,4 +779,62 @@ void purgeInstanceFilter() {
...
+
+                    // Wait for all tasks to complete
+                    try {
+                        List<Integer> results = ctx.allOf(parallelTasks).await();
+                        ctx.complete(results);
+                    }catch (CompositeTaskFailedException e){
+                        assertNotNull(e);
+                        assertEquals(2, e.getExceptions().size());
+                        assertEquals(ExecutionException.class, e.getExceptions().get(0).getClass());
+                        assertEquals(ExecutionException.class, e.getExceptions().get(1).getClass());
```
Comment (cgillum) [inline client/src/test/java/com/microsoft/durabletask/IntegrationTests.java:804]: What is an `ExecutionException`?  I would have expected the type of `e.getException()` to be `TaskFailedException`. Is it possible to do this? I think that would make for a better developer experience because the `TaskFailedException` is the most interesting thing for code to inspect.

**Review by cgillum — COMMENTED** [review]
I think we're very close on this one! There are a couple changes we should make to the JavaDoc comments and one suggested change about the organization of the inner exceptions.

File: client/src/test/java/com/microsoft/durabletask/IntegrationTests.java (hunk 17 above)
Comment (shreyas-gopalakrishna) [reply client/src/test/java/com/microsoft/durabletask/IntegrationTests.java:804]: CompletableFuture.get() here is throwing the ExecutionException. We will have to create a new TaskFailedException but do not have all failure details like below.
```java
public <V> Task<List<V>> allOf(List<Task<V>> tasks) {
      Helpers.throwIfArgumentNull(tasks, "tasks");

      CompletableFuture<V>[] futures = tasks.stream()
              .map(t -> t.future)
              .toArray((IntFunction<CompletableFuture<V>[]>) CompletableFuture[]::new);

      return new CompletableTask<>(CompletableFuture.allOf(futures)
              .thenApply(x -> {
                  List<V> results = new ArrayList<>(futures.length);

                  // All futures are expected to be completed at this point
                  for (CompletableFuture<V> cf : futures) {
                      try {
                          results.add(cf.get());
                      } catch (Exception ex) {
                          results.add(null);
                      }
                  }
                  return results;
              })
              .exceptionally(throwable -> {
                  ArrayList<Exception> exceptions = new ArrayList<>(futures.length);
                  for (CompletableFuture<V> cf : futures) {
                      try {
                          cf.get(); // This throws ExecutionException
                      } catch (Exception ex) {
                          // We can create a TaskFailedException here but we will have to parse the exception for taskId, name and other details                           
                         exceptions.add(ex);
                      }
                  }
                  throw new CompositeTaskFailedException(exceptions.get(0).getCause().getMessage(), exceptions);
              })
      );
  }
```



image

Comment (cgillum) [reply client/src/test/java/com/microsoft/durabletask/IntegrationTests.java:866]: I see, so `CompletableFuture.get()` always throws this. Then instead of adding `ExecutionException` to the list of exceptions, can we instead just add the inner `TaskFailedException` directly? Something like this:

```java
try {
    cf.get();
} catch (ExecutionException ex) {
    // The cause is expected to be TaskFailedException
    exceptions.add(ex.getCause());
} catch (Exception ex) {
    // Not expected, but just in case we see an exception we don't know about
    exceptions.add(ex);
}
```

That way we don't need to expose `ExecutionException` in user code.

File: client/src/main/java/com/microsoft/durabletask/TaskOrchestrationExecutor.java [hunk 18]
```diff
@@ -173,23 +171,34 @@ public <V> Task<List<V>> allOf(List<Task<V>> tasks) {
...
+                        for (CompletableFuture<V> cf : futures) {
+                            try {
+                                cf.get();
+                            } catch (ExecutionException ex) {
+                                exceptions.add((Exception) ex.getCause());
+                            } catch (Exception ex){
+                                exceptions.add(ex);
+                            }
+                        }
+                        throw new CompositeTaskFailedException(exceptions.get(0).getMessage(), exceptions);
```
Comment (cgillum) [inline client/src/main/java/com/microsoft/durabletask/TaskOrchestrationExecutor.java:199]: I wonder if it would be better to have a more generic message here. Otherwise, developers may not realize that there could be more than one failure. How about something like this?
```suggestion
                        throw new CompositeTaskFailedException(
                            String.format(
                                "%d out of %d tasks failed with an exception. See the exceptions list for details.", 
                                exceptions.size(),
                                futures.length),
                            exceptions);
```

**Review by cgillum — COMMENTED** [review]
Sorry, one more thing I noticed in my final pass through the code.

File: client/src/main/java/com/microsoft/durabletask/TaskOrchestrationExecutor.java (hunk 18 above)
Comment (shreyas-gopalakrishna) [reply client/src/main/java/com/microsoft/durabletask/TaskOrchestrationExecutor.java]: My thought was to inform the developers with the first exception message. But this message is more informative.

**Review by cgillum — APPROVED** [review]
This looks great! Thanks for doing this work!
